src/App.tsx

- https://github.com/DevKor-github/air-fryer-fe/issues/4 
- dev 브랜치 들어갈 때 자동 배포 잘 되는지 체크 슛 
-

test: 배포 잘 되남

---

src/pages/PostPages/StepIndicator/index.tsx
src/pages/PostPages/StepIndicator/style.css.ts
src/pages/PostPages/WriteLayout/index.tsx
src/pages/PostPages/WriteLayout/navigator.tsx

- #38 
얘를 만들었습니다
- 이거 트랜지션 피그마에 정의되어 있나요? 걍 제 맘대로 넣어놨는데

feat: step indicator 구현

---

src/features/post/components/MultilineInputField/index.tsx
src/features/post/components/MultilineInputField/style.css.ts
src/features/post/components/StepFunnel/Step6/index.tsx

- 100만원 미만 어쩌고
- 멀티라인 인풋필드도 디자인 조금 수정함
- 모르는 척하기

fix: step6 안내문 한줄 추가

---

package.json
panda.config.ts
src/common/components/Drawer/BackLayer.tsx
src/common/components/Drawer/DrawerBody.tsx
src/common/components/Drawer/index.tsx
src/common/components/Drawer/style.css.ts
src/common/hooks/useDrawer.tsx
src/features/home/components/SearchControls/index.tsx
yarn.lock

- Resolves #77 
https://github.com/user-attachments/assets/1b3a5477-2abd-4d53-97fd-56b40ee6e067
- 짜잔
- useDrawer라는 훅과 Drawer 컴포넌트로 바텀시트를 만들어뒀음
- 호오오오오옥시나 선생님 파트에서 쓰실 일이 있다면 설명해놓은대로 + 예시로 만들어놓은거처럼 쓰시면 됩니다
- 코드 구조 한번 보고 피드백 남겨주세요... useDrawer 선언해두고 여기서 나온 애를 Drawer에 수동으로 넣어줘야 하는거라 구조 솔직히 좀 맘에 안듦
- 구현하면서 `motion`이라는 라이브러리를 썼습니다. 애니메이션 구현해주는 친구임
- 근데 아직 디자이너들끼리 바텀시트 디자인이 확정이 안났대서 구체적인 디자인은 안해둠
- `yarn` 한번 해주삼

[#77] 바텀시트 구현구현 !

---

src/common/components/ItemTokenList/index.tsx
src/features/home/components/ItemCard/PriceToken/index.tsx
src/features/home/components/ItemCard/PriceToken/style.css.ts
src/features/home/components/ItemCard/index.tsx
src/features/home/components/ItemCard/style.css.ts
src/features/home/types.ts

- 없삼
- 회의 때 나온 홈화면 페이지 변경사항 적용함
- 태그 4개여도 스크롤 생기는 경우 있어서 일단은 항상 3개만 보여지게 해놨는데
나중에 여유로울때 태그 길이에 따라 보여지는 개수 다르게 뜨도록 고쳐놓을게요

fix: 25-07-28 (5분 PR 가능)

---

package.json
panda.config.ts
src/common/components/Pagination/index.tsx
src/common/components/Pagination/style.css.ts
src/common/components/Spinner/index.tsx
src/common/components/Spinner/style.css.ts
src/common/utils/useIntersect.ts
src/common/utils/wsClient.ts
src/features/chatList/api/useGetChatList.ts
src/features/chatList/components/ChatList/index.tsx
src/features/chatList/types.ts
src/features/chatRoom/api/useGetChatRoom.ts
src/features/chatRoom/api/useGetLoadChat.ts
src/features/chatRoom/components/ChatMessageContents/index.tsx
src/features/chatRoom/components/ChatMessageContents/style.css.tsx
src/features/chatRoom/components/ChatRoomLayout/ChatRoomContent/index.tsx
src/features/chatRoom/components/ChatRoomLayout/ChatRoomContent/style.css.ts
src/features/chatRoom/components/ChatRoomLayout/ChatRoomFooter/index.tsx
src/features/chatRoom/components/ChatRoomLayout/ChatRoomHeader/index.tsx
src/features/chatRoom/types.ts
src/features/home/apis/useGetItemCount.ts
src/features/home/apis/useGetItemList.ts
src/features/home/components/ItemList/index.tsx
src/features/home/components/RecentList/index.tsx
src/libs/constants/index.ts
src/pages/ChatPage/index.tsx
src/pages/ChatRoomPage/index.tsx
src/pages/SearchPage/index.tsx
yarn.lock

- Resolves #91 
chat list, chat room message 페이지네이션 적용
- 재훈씨에게 커서 데이터 없이도 enter 작동하도록 바꿔달라고 말해놨슴니다

[Feat] chat 페이지네이션

---

src/features/detail/apis/useGetItemStatus.ts
src/features/detail/apis/usePostChatroom.ts
src/features/detail/components/BottomActions/index.tsx
src/pages/DetailPage/index.tsx

- Resolves #141 
- Resolves #124 
- 게시글 상세 페이지에서 채팅 버튼을 누르면 이제 채팅방으로 이동 됩니다
- 비로그인 사용자의 경우 -> 로그인 페이지로 보냄
- 로긘 사용자의 경우 -> 채팅방이 없는 경우 개설 -> 그 채팅방으로 보냄
- 있는 경우 그 채팅방으로 바로 보냄
- 그리고 개설된 PICK이 있다면 아래쪽 버튼도 다르게 보이게 하려 하는데 그건 pick 구현을 안해서라 테스트가 아직 불가함. TODO로 달아뒀어요

채팅룸 만들기 구현 !

---

src/common/components/CustomAlert/index.tsx
src/common/components/Drawer/DrawerBody.tsx
src/common/components/Drawer/index.tsx
src/common/components/Drawer/style.css.ts
src/features/chatList/components/ChatList/index.tsx
src/features/detail/components/DetailHeader/index.tsx
src/features/detail/components/OptionDrawer/index.tsx
src/features/detail/components/OptionDrawer/style.css.ts
src/features/post/components/WriteLayout/header.tsx

- #129 
- 케밥 메뉴 누르면
- 수정하기 / 삭제하기 나오고
- 수정하기 누르면 수정 페이지로 연결 (아직 안함)
- 삭제하기 누르면 진짜 삭제 Alert 나오고, 여기서 예 삭제해요 누르면 삭제됨

게시글 삭제 모달 만들기

---

src/common/utils/wsClient.ts
src/features/chatRoom/components/ChatMessageContents/index.tsx
src/features/chatRoom/components/ChatRoomLayout/ChatRoomContent/index.tsx
src/features/chatRoom/components/ItemInfo/style.css.ts
src/features/chatRoom/components/MyChat/index.tsx
src/features/chatRoom/types.ts

feat: 채팅 읽음 처리

---

src/common/components/CustomAlert/index.tsx
src/features/chatList/api/useGetInProgess.ts
src/features/chatList/components/ChatDrawer/index.tsx
src/features/chatList/components/ChatList/index.tsx

- Resolves #177 
- exit 시에 대여 중인지 확인
-

feat: 대여 중인 약속 api 추가

---

src/features/chatList/components/ChatList/index.tsx
src/features/chatList/types.ts
src/features/detail/components/DetailHeader/index.tsx
src/features/detail/components/OptionDrawer/index.tsx
src/features/report/apis/usePostReport.ts
src/pages/ChatPage/index.tsx
src/pages/ReportPage/index.tsx
src/pages/ReportPage/style.css.ts
src/pages/routes.tsx

feat: 신고하기

---

src/features/my/apis/usePostLogout.ts
src/features/my/components/MyTrade/index.tsx
src/features/pickList/components/Btn/index.tsx
src/features/pickList/components/PickItemList/style.css.ts
src/pages/PickPage/index.tsx
src/pages/ReviewPage/index.tsx

feat: toast:

---

src/features/pick/components/DetailBottom/index.tsx
src/pages/PickDetailPage/index.tsx
src/pages/PickDetailPage/style.css.ts

채팅으로 버튼, 얼럿 띄우기

---

src/App.tsx
src/common/apis/usePatchFCMToken.ts
src/common/apis/useTestFCMToken.ts
src/common/components/NotificationProvider/index.tsx
src/common/store/FCMStore.ts
src/libs/types/native.ts

FCM token 발급 받고 웹뷰에서 서버로 보내기

---

src/common/components/MainTopBar/index.tsx
src/common/utils/parseDate.ts
src/features/likedList/components/itemList/index.tsx
src/features/notification/apis/useGetNotification.ts
src/features/notification/components/NotificationItemCard/index.tsx
src/features/notification/components/NotificationItemCard/style.css.ts
src/features/notification/components/NotificationList/index.tsx
src/features/notification/types.ts
src/features/pick/components/DetailBottom/index.tsx
src/features/pickList/components/PickItemList/index.tsx
src/features/pickList/components/TradeInfo/index.tsx
src/features/pickList/components/TradeInfo/style.css.ts
src/libs/queryKeys.ts
src/pages/LikedListPage/index.tsx
src/pages/NotificationPage/index.tsx
src/pages/NotificationPage/style.css.ts
src/pages/routes.tsx

- 아 뭔가 날짜 관련해서 고쳐야 할 게 많음 넘 헷갈림;;

feat: 알림 내역

---

src/pages/ReviewPage/index.tsx

feat: 리뷰 얼럿 띄우기

---

src/features/chatRoom/components/ChatMessageContents/index.tsx
src/features/chatRoom/components/ChatRoomLayout/ChatRoomContent/index.tsx
src/features/chatRoom/components/InputField/index.tsx
src/features/chatRoom/components/ItemInfo/index.tsx
src/features/chatRoom/components/ItemInfo/style.css.ts
src/features/chatRoom/components/PickChat/index.tsx
src/features/chatRoom/components/PickChat/style.css.ts
src/features/chatRoom/types.ts
src/features/notification/components/NotificationItemCard/index.tsx
src/features/notification/components/NotificationItemCard/style.css.ts
src/pages/ChatRoomPage/index.tsx

삭제된 게시글 처리

---

src/features/notification/apis/useGetNotification.ts
src/features/notification/components/NotificationItemCard/index.tsx
src/features/notification/components/NotificationList/index.tsx
src/features/notification/types.ts
src/pages/NotificationPage/index.tsx

[fix] notification 바뀐 api 대응

---

src/features/chatRoom/components/ItemInfo/index.tsx
src/features/chatRoom/components/ItemInfo/style.css.ts
src/features/notification/components/NotificationItemCard/index.tsx
src/features/notification/components/NotificationItemCard/style.css.ts
src/features/notification/components/NotificationList/index.tsx

삭제된 게시글에 대한 처리 (토스트, 투명도)

---

src/features/pickList/components/PickItemList/index.tsx
src/features/pickList/components/TradeInfo/index.tsx
src/pages/PickDetailPage/index.tsx

- Resolves #218 
- 머지하기 전에 디자이너들의 동의가 필요함

pick 페이지 라벨 문구 수정하기
